# Test application values for namespace chart
# This file provides sample values for testing the deployment

# ==============================
# MANDATORY FIELDS
# ==============================

# Application name - used for labeling resources
#appName: "test-application"

appName: data-platform-poc
snowApmId: APM121000

# Snow Application ID - used for namespace naming and labeling
# Must follow the format APM followed by 8 digits (e.g., APM12345678)
#snowApmId: "apm12345678"

# GitLab Project IDs - used for annotations to link resources to GitLab projects
gitlabProjIds: 
  - "12345"
  - "67890"

# ==============================
# ENVIRONMENTS CONFIGURATION
# ==============================

environments:
  # Define environments with specific configurations
  sbox:
    labels:
      environment-type: sandbox
      cost-center: dev-ops
    annotations:
      platform.eks.ukatru.cloud/description: "Sandbox environment for testing"
    resourceQuota:
      hard:
        limits.cpu: "4"
        limits.memory: 8Gi
        requests.cpu: "2"
        requests.memory: 4Gi
        pods: "10"
  
  dev:
    labels:
      environment-type: development
      cost-center: dev-ops
    annotations:
      platform.eks.ukatru.cloud/description: "Development environment"
    resourceQuota:
      hard:
        limits.cpu: "8"
        limits.memory: 16Gi
        requests.cpu: "4"
        requests.memory: 8Gi
        pods: "20"
  
  test:
    labels:
      environment-type: testing
      cost-center: qa
    annotations:
      platform.eks.ukatru.cloud/description: "Testing environment"
    resourceQuota:
      hard:
        limits.cpu: "12"
        limits.memory: 24Gi
        requests.cpu: "6"
        requests.memory: 12Gi
        pods: "30"
  
  prod:
    labels:
      environment-type: production
      cost-center: operations
    annotations:
      platform.eks.ukatru.cloud/description: "Production environment"
    resourceQuota:
      hard:
        limits.cpu: "16"
        limits.memory: 32Gi
        requests.cpu: "8"
        requests.memory: 16Gi
        pods: "40"
