{{- range $env, $envConfig := .Values.environments }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
  annotations:
    "helm.sh/hook-weight": "5"
  labels:
    app: {{ $.Values.appName }}
    platform.eks.ukatru.com/snow-app-id: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/name: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/instance: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/component: limit-range
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: {{ $.Values.snowApmId }}
    platform.k8s.ukatru.cloud/env: {{ $env }}
spec:
  {{ include "validateLimitRange" $envConfig.limitRange | nindent 2 }}
{{- end }}
