{{- range $env, $envConfig := .Values.environments }}
{{- if eq (include "shouldDeployEnvironment" (dict "env" $env "clusterEnv" $.Values.clusterEnv)) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
  annotations:
    "helm.sh/hook-weight": "-10"
    platform.eks.ukatru.cloud/gitlab-project-ids: {{ join "," $.Values.gitlabProjIds }}
    {{- if $envConfig.annotations }}
    {{- toYaml $envConfig.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: {{ $.Values.appName }}
    platform.eks.ukatru.com/snow-app-id: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/name: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/instance: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/component: namespace
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: {{ $.Values.snowApmId }}
    platform.k8s.ukatru.cloud/env: {{ $env }}

    {{- if $envConfig.labels }}
    {{- toYaml $envConfig.labels | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
