{{- range $env, $envConfig := .Values.environments }}
{{- if eq (include "shouldDeployEnvironment" (dict "env" $env "clusterEnv" $.Values.clusterEnv)) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-namespace-network-policy
  namespace: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
  annotations:
    "helm.sh/hook-weight": "0"
    platform.k8s.ukatru.cloud: |
      1. Ensure that all pods within the same namespace can communicate with each other freely
      2. Ensure the ELB can route traffic to the pod
      3. Ensure kube-system and grafana can reach the pods
  labels:
    app: {{ $.Values.appName }}
    platform.eks.ukatru.com/snow-app-id: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/name: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/instance: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/component: network-policy
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: {{ $.Values.snowApmId }}
    platform.k8s.ukatru.cloud/env: {{ $env }}

spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from pods in the same namespace
    - from:
        - podSelector: {}
    # Allow traffic from specific namespaces
    - from:
        {{- $allowedNamespaces := (list "grafana") }}
        {{- range $ns := $allowedNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
        {{- end }}
    # Allow traffic from external subnets
    {{- if $.Values.externalSubnetCidrs }}
    - from:
        {{- range $cidr := $.Values.externalSubnetCidrs }}
        - ipBlock:
            cidr: {{ $cidr }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
