{{- range $env, $envConfig := .Values.environments }}
{{- if eq (include "shouldDeployEnvironment" (dict "env" $env "clusterEnv" $.Values.clusterEnv)) "true" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
  annotations:
    "helm.sh/hook-weight": "5"
  labels:
    app: {{ $.Values.appName }}
    platform.eks.ukatru.com/snow-app-id: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/name: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/instance: {{ include "namespace.generateName" (dict "env" $env "root" $) }}
    app.kubernetes.io/component: resource-quota
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: {{ $.Values.snowApmId }}
    platform.k8s.ukatru.cloud/env: {{ $env }}
spec:
  {{ include "validateResourceQuota" $envConfig.resourceQuota | nindent 2 }}
{{- end }}
{{- end }}
